- name: copy roboshop config file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
- name: Installing MongoDB
  ansible.builtin.yum:
    name: mongodb
    state: latest

- name: Replace text
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.0'
    replace: '0.0.0.0'
- name: Start mongodb
  ansible.builtin.service:
    state: restarted
    name: mongod
    enabled: true
