- name: configuring ERlang repos
  ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: configuring rabbitmq repos
  ansible.builtin.shell: https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: install Rabbitmq server
  ansible.builtin.shell: dnf install rabbitmq-server -y

#- name: Install RabbitMQ server
#  ansible.builtin.yum:
#    name: rabbitmq-server
#    state: installed

- name: Install RabbitMQ server
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add Application user
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present