- name: add application user
  ansible.builtin.user:
    name: roboshop

- name: Remove old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes


- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
    dest: /app
    remote_src: yes







#  app_presetup() {
#
#    echo -e "${color} adding user ${nocolor}"
#
#    id roboshop &>>log_file
#    if [ $? -eq 1 ]; then
#    useradd roboshop &>>log_file
#    fi
#    stat_check $?
#    echo -e "${color} create app directory ${nocolor}"
#    rm -rf ${app_path} &>>log_file
#    mkdir ${app_path} &>>log_file
#    stat_check $?
#
#    echo -e "${color} Download the application code to created app directory ${nocolor}"
#    curl -o /tmp/${component}.zip https://roboshop-artifacts.s3.amazonaws.com/${component}.zip &>>log_file
#    cd ${app_path} &>>log_file
#    stat_check $?
#
#    echo -e "${color} extract the content ${nocolor}"
#    unzip /tmp/${component}.zip &>>log_file
#    stat_check $?
#
#  }
