- name: Install NodeJS
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Load Schema
  ansible.builtin.shell: mongo --host mongodb-dev.devopsb73.tech </app/schema/{{ component }}.sql




#mysql_schema_setup() {
#echo -e "${color} Install MySQL Client ${nocolor}"
#yum install mysql -y  &>>$log_file
#stat_check $?
#
#echo -e "${color} Load Schema ${nocolor}"
#mysql -h mysql-dev.devopsb73.tech -uroot -p${mysql_root_password} </app/schema/${component}.sql   &>>$log_file
#stat_check $?